### ISSUE TITLE
Inicio

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#1]

**Comment by carlofav12** [comment]
Iniciar con el boceto de figma

![Image](https://github.com/user-attachments/assets/cebd664b-01d2-40e3-ae44-5e5dab64f96f)

**Comment by Usmpmarkp** [comment]
![image](https://github.com/user-attachments/assets/ce636f04-f777-42a0-a315-656f874da31a)
Se finalizo la vista Inicio
