### ISSUE TITLE
Filtro en Catalogo

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#14]
Hacer que funcione el filtro de categorias![Image](https://github.com/user-attachments/assets/49e5cf6c-1ab4-4d74-8062-4e9adcad94c6)

**Comment by Adriancas28** [comment]
Realizado

**Comment by Adriancas28** [comment]
![image](https://github.com/user-attachments/assets/14fa8eb8-bbd8-4ce6-b29d-6949e26e337f)
Ejemplo de filtro de precio menor a meyor
