### ISSUE TITLE
Mejorar Vistas

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#16]
Elegir la mejor paleta de colores para todas las vistas de la pagina y mejorar las ya existentes
![Image](https://github.com/user-attachments/assets/f41db343-8b47-4798-94b2-8aa0106829fc)
![Image](https://github.com/user-attachments/assets/ec01ea95-caa8-4787-ad46-170dbcfb1975)

**Comment by Usmpmarkp** [comment]
![image](https://github.com/user-attachments/assets/fffc353b-c550-48d1-b1cb-6ccdf6fd22e5)
Eligiendo nuestra paleta de colores

**Comment by Usmpmarkp** [comment]
![image](https://github.com/user-attachments/assets/ddb9e7f1-0b46-4c4c-b23a-7c70c50d51a8)
Cambiando Fondo y Navbar según a nuestra paleta de colores

**Comment by carlofav12** [comment]
Mejora en vista Catalogo y Home
![Image](https://github.com/user-attachments/assets/1199ba1d-9f7f-46f6-be03-671cbe8412f0)
![Image](https://github.com/user-attachments/assets/e49e2719-1ac6-4cde-a6b8-ed9b2247790f)

**Comment by Adriancas28** [comment]
Mejorando la vista Nosotros segun la paleta de colores y diseño
![image](https://github.com/user-attachments/assets/62bca93a-37e9-42a2-9bc5-5c397781c76f)

![image](https://github.com/user-attachments/assets/d4f57049-dbdd-4b0b-8680-768c8ee2528f)
