### ISSUE TITLE
Login-Administrador

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#17]
Ingresar el login para el administrador
![Image](https://github.com/user-attachments/assets/7a14fb83-46a6-4038-8448-685bf4c15c57)

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/98eaf5db-f0fe-4b07-a506-b5607d60a35b)
Se realizo la interfaz de de inicio de Admin  y el inicio de sesion para el logeo del dashboard admin

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/62383ab1-b901-48b1-8cf4-933183bbe9ec)
Base de datos de administradores
