### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#2]

**Comment by carlofav12** [comment]
Completar Navbar inicial de boceto en figma

![Image](https://github.com/user-attachments/assets/804c864d-c73c-46c3-bf76-82327c5dac8b)

**Comment by Usmpmarkp** [comment]
Navbar Completado 
![Image](https://github.com/user-attachments/assets/b26b41f0-778a-47fc-a97e-050abedc49be)
