### ISSUE TITLE
Login Usuario

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#29]
Conseguir que la vista del usuario sea lo más agradable posible y remarcar el carrito de compras

**Comment by Usmpmarkp** [comment]
![image](https://github.com/user-attachments/assets/aaaf1a48-fe1d-4959-b388-d6d79b58437f)
![image](https://github.com/user-attachments/assets/0337ae65-e64a-4814-9426-62113eb3df12)
![image](https://github.com/user-attachments/assets/5cfc8f75-5b22-45aa-9b20-284cee077274)
![image](https://github.com/user-attachments/assets/91c27d5a-1fc2-4f36-a665-e2f3fc0a9fb7)
![image](https://github.com/user-attachments/assets/3d98899f-d355-4bdd-98b8-2792d0ee535d)
Se realizo cambios internos sobre administrar tu cuenta
