### ISSUE TITLE
Contacto y Nosotros

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#3]

**Comment by carlofav12** [comment]
Avanzar con concepto de contacto y nosotros en base al figma

![Image](https://github.com/user-attachments/assets/45e62d7d-c6e1-4513-8186-cffde7c972ea)

**Comment by Adriancas28** [comment]
Realizado

**Comment by Usmpmarkp** [comment]
![image](https://github.com/user-attachments/assets/e1a84b35-f1a2-4dd5-bb9f-3e569ea2f444)
![image](https://github.com/user-attachments/assets/f1a36e92-d370-4811-b97b-c042c458724d)
![image](https://github.com/user-attachments/assets/92b08e21-ebf8-4c3a-b49f-bfd6065211e4)
Realizando la vista de Nosotros
