### ISSUE TITLE
Bloquear Vista restringidas

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#30]
Evitar que usuarios puedan acceder a vistas que no deberían

**Comment by Adriancas28** [comment]
![image](https://github.com/user-attachments/assets/04cfb48a-4eb2-4987-991c-40c1c5008439)
Autorizaciones de urls por roles.
![image](https://github.com/user-attachments/assets/b1f6dbb4-618a-485f-8841-5a42ad3b54d6)
Configurando el archivo Porgram.cs

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/438ed699-d9e0-4017-9c4c-f25032993409)
Visualizacion del acceso negado a la vista Admin sin credenciales

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/d145c4f8-1603-4a80-9727-0d3d39a075d3)
Acciones completadas del admin con la mejora del flujo admin
