### ISSUE TITLE
Investigar apis como Enviamas-paycomet-etc

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#33]
Investigar apis que tengan Relacion con pasarela de pagos, y seguimientos de envíos

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/a3292efe-b5d3-42a9-ad4b-f1e068ea1eeb)
Investacion del API NewsApi para buscar noticiales mundiales

**Comment by carlofav12** [comment]
consumo de api de mercadopago para pagos de usuarios
![Image](https://github.com/user-attachments/assets/176314fa-02b9-4157-a692-51a5e2fc48dd)

![Image](https://github.com/user-attachments/assets/58ae8eeb-ddc4-41a0-80ea-7afac7bf8520)

**Comment by Usmpmarkp** [comment]
![image](https://github.com/user-attachments/assets/fe36a2bd-5357-4b08-ab39-cd02913a2bad)
Consumo de Api para el apartado de Frase del Dia
