### ISSUE TITLE
Generar Swagger ui

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#34]
generar el swagger file para productos y usuario u otro en consideración
![Image](https://github.com/user-attachments/assets/1c31d6ee-3514-442a-9849-fc54639ee50d)

**Comment by carlofav12** [comment]
se genera swagger file para los usuarios tanto para mostrar en general, por id, añadir, y eliminar
![Image](https://github.com/user-attachments/assets/6389fd97-9c6f-4adb-841b-ee5513b24fa1)
![Image](https://github.com/user-attachments/assets/6100c7c0-7571-4477-88f3-e75c99c57241)
![Image](https://github.com/user-attachments/assets/7a015905-4705-46fd-8865-4f9041d7288c)

**Comment by Usmpmarkp** [comment]
![Image](https://github.com/user-attachments/assets/cf00aa74-ff3b-4ced-82e6-3b46e844736e)
![Image](https://github.com/user-attachments/assets/22e22652-aeaf-464f-b659-f4b514696b9e)

**Comment by carlofav12** [comment]
Generación final de archivo swagger json 
![Image](https://github.com/user-attachments/assets/99c9d745-ce80-4ff2-8fcf-2bafdc319236)
