### ISSUE TITLE
API-frase

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#42]
El api de frase del día no funciona como debería
![Image](https://github.com/user-attachments/assets/a036e7a2-ca3d-46e6-9cbe-210b05d0e37d)
buscar sustituto a api- frase del día 
![Image](https://github.com/user-attachments/assets/d1a5289b-06fb-4c73-8391-dbbc1a23d90d)

**Comment by Usmpmarkp** [comment]
se volvio a restaurar
