### ISSUE TITLE
Utilizar ML net para clasificacion de comentarios

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#43]
Utilizar Ml net para clasificar comentarios positivos y negativos en contacto
![Image](https://github.com/user-attachments/assets/9360f172-9df1-445a-a305-825348804558)

**Comment by Usmpmarkp** [comment]
![Image](https://github.com/user-attachments/assets/adef58e9-c456-42dc-ad65-f1b41676c576)
Se mejora esta vista y se añadió el mensaje de clasificación con MLnet
