### ISSUE TITLE
Registro Usuario

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#5]
Avanzar con el registro de usurio con los siguientes valores
 
![Image](https://github.com/user-attachments/assets/d50ee554-f7af-4ab8-9120-51c32bdfdfbf)

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/16fbcab0-27c9-4180-af1b-10cb4efa69f8)
Se realizo la creacion del formulario registro

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/b54d1d11-4c41-4ad8-bdb8-5b551f9d3300)
Base de datos listado
