### ISSUE TITLE
Mejora Vistas de carro

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#50]
Mejorar las vista de usuario respecto a sus compras

**Comment by Usmpmarkp** [comment]
![Image](https://github.com/user-attachments/assets/84b6f154-3295-4b1b-84c1-7b39a76cc539)
![Image](https://github.com/user-attachments/assets/1eba0b4b-7d02-40ca-8c30-40ff002ab4dd)
![Image](https://github.com/user-attachments/assets/98c61250-8370-4480-8ac4-88f05fe01330)
Se ha mejora la vista del carrito de compras, como también se le añadió notificaciones en el carrito mientras va cargando sus productos y por ultimo se añadió un historial de compras donde el usuario podrá ver el detalle de su compra
