### ISSUE TITLE
Mejora vista completando compra

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#53]
Mejorar las vistas finales de compra de usuario

**Comment by Usmpmarkp** [comment]
![Image](https://github.com/user-attachments/assets/8eeeb1dc-62bc-4c70-956d-c10d12bd4d8b)
![Image](https://github.com/user-attachments/assets/fc78371b-2ce7-487b-b57a-a5689cfecb47)
Se mejorado la vista del historial de compras y también se podrá ver el historial de las compras desde la vista admin
