### ISSUE TITLE
Arreglar api de noticias

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#56]
arreglar el api de noticias 
![Image](https://github.com/user-attachments/assets/3526016d-2ddf-4e8a-9484-7a9294d47570)

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/6c2b12f8-5759-4176-a2ec-49b47c4f230a)
Se actualizo correctamente el Api-Noticias
