### ISSUE TITLE
Mejoras vistas-enlaces

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#58]
Mejorar vistas y enlaces como:
1.- Pestaña de Nosotros Footer debe redirigir a nosotros 
![Image](https://github.com/user-attachments/assets/322c44e9-0b51-4ddb-a126-c9d3f66c51f8)

2.- Corregir nombre de pestaña (agregar en que se encuentra)
![Image](https://github.com/user-attachments/assets/86cbca3a-5961-4898-81f8-9a057c0a0429)

3.- Cambiar el contenido del correo de verificación
![Image](https://github.com/user-attachments/assets/01c833fb-0364-49ef-9ff2-4d5e43364a3f)
![Image](https://github.com/user-attachments/assets/89f07e68-6a9f-4744-a367-3552126faf4f)
Talvez agregar una imagen del correo que le debe llegar
![Image](https://github.com/user-attachments/assets/4f9d8702-9cf4-48a6-bb25-a2acbe7b4b44)

3.2- Cambiar el mensaje de confirmación
![Image](https://github.com/user-attachments/assets/3d750165-75a9-45e0-b073-0b34a2e7652e)

4.- Poner icono de aplicativo en pestaña
![Image](https://github.com/user-attachments/assets/5d27e90e-cd13-4815-8ca2-95b839bb34fb)

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/5572e69d-1e9c-4ad3-9fc2-cfa0badf6fa3)
![Image](https://github.com/user-attachments/assets/e08351b3-af61-4184-91bf-51c67e86cab6)
Direccionamiento correguido tanto para la vista de usuario como la de administrador

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/a050a4f2-80bf-43a0-9fec-b5fac3be68e0)
Correguido el nombre de pestañas

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/52022443-bdcd-49a8-ae57-ed5dc4d85ffd)
Se añadio la imagen de guia de verificacion de correo .

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/853df870-8a3b-433f-9df2-48427bef7a8e)
ARREGLO DEL ICONO DE LA PRESENTACION DE LA PAGINA WEB

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/6a282116-3a2d-4bcd-9348-799de9e9e2bd)
