### ISSUE TITLE
Agregar Sensibilidad Admin

### ISSUE THREAD

**Issue by carlofav12** [carlofav12/XDeco#60]
agregar la sensibilidad de comentario para Administrador
![Image](https://github.com/user-attachments/assets/4ccfc546-26fa-4d2b-9ef8-b937500cd7c9)

**Comment by JhowillSC** [comment]
![Image](https://github.com/user-attachments/assets/f19eb435-c6a6-4722-aeb4-1c579a8ff58f)
Se agrego la sensibilidad en la vista Administrador
